export const ITEMS = [
  {
    id: "coffeeMachine",
    image: "img/coffeeMachine.jpg",
    alt: "coffeeMachine",
    title: "Кофемашина PHILIPS EP1224/00, серый/черный",
    count: 1,
    price: 29990,
    total: 0,
  },
  {
    id: "giroscooter",
    image: "img/giroscooter.jpg",
    alt: "giroscooter",
    title: 'Гироскутер MIZAR MZ10,5CN, 10.5", карбон',
    count: 1,
    price: 12990,
    total: 0,
  },
  {
    id: "MFU",
    image: "img/MFU.jpg",
    alt: "table MENU",
    title: "МФУ лазерный CANON i-Sensys MF445dw, A4, лазерный, черный",
    count: 1,
    price: 35310,
    total: 0,
  },
  {
    id: "monitor",
    image: "img/monitor.jpg",
    alt: "monitor",
    title: 'Монитор игровой ACER Nitro RG241YPbiipx 23.8" черный',
    count: 1,
    price: 16800,
    total: 0,
  },
  {
    id: "mouse",
    image: "img/mouse.jpg",
    alt: "mouse",
    title: "Мышь A4TECH Bloody V3, игровая, оптическая, проводная, USB, черный",
    count: 1,
    price: 960,
    total: 0,
  },
  {
    id: "photoAction",
    image: "img/photoAction.jpg",
    alt: "photoAction",
    title: "Экшн-камера DIGMA DiCam 310 4K, WiFi, черный",
    count: 1,
    price: 2290,
    total: 0,
  },
  {
    id: "quadrocopter",
    image: "img/quadrocopter.jpg",
    alt: "quadrocopter",
    title: "Квадрокоптер DJI Mini 2 MT2PD Fly More Combo с камерой, серый",
    count: 1,
    price: 60990,
    total: 0,
  },
  {
    id: "smartSound",
    image: "img/smartSound.jpg",
    alt: "smartSound",
    title: "Умная колонка ЯНДЕКС c голосовым помощником Алисой, серебристый",
    count: 1,
    price: 5670,
    total: 0,
  },
  {
    id: "tablet",
    image: "img/tablet.jpg",
    alt: "tablet",
    title: "Планшет DIGMA Optima 7 Z800 Android 10.0 серебристый",
    count: 1,
    price: 9490,
    total: 0,
  },
  {
    id: "trimmer",
    image: "img/trimmer.jpg",
    alt: "trimmer",
    title: "Триммер PHILIPS HC3521/15 серебристый/черный",
    count: 1,
    price: 2290,
    total: 0,
  },
  {
    id: "VR",
    image: "img/VR.jpg",
    alt: "VR",
    title: "Шлем виртуальной реальности HTC Vive PRO Eye EEA, черный/синий",
    count: 1,
    price: 11960,
    total: 0,
  },
  {
    id: "watchBlack",
    image: "img/watchBlack.jpg",
    alt: "watchBlack",
    title: 'Фитнес-трекер HONOR Band 5 CRS-B19S, 0.95", черный',
    count: 1,
    price: 2390,
    total: 0,
  },
  {
    id: "watchGreen",
    image: "img/watchGreen.jpg",
    alt: "watchGreen",
    title: 'Смарт-часы AMAZFIT Bip U, 1.43", зеленый / зеленый',
    count: 1,
    price: 4490,
    total: 0,
  },
  {
    id: "watchPink",
    image: "img/watchPink.jpg",
    alt: "watchPink",
    title: 'Фитнес-трекер HONOR Band 5 CRS-B19S, 0.95", розовый',
    count: 1,
    price: 2390,
    total: 0,
  },
  {
    id: "waterAir",
    image: "img/waterAir.jpg",
    alt: "waterAir",
    title: "Увлажнитель воздуха STARWIND SHC1322, 3л, белый",
    count: 1,
    price: 1650,
    total: 0,
  },
  {
    id: "WaveAir",
    image: "img/WaveAir.jpg",
    alt: "WaveAir",
    title: "Пылесос SINBO SVC 3497, 2500Вт, синий/серый",
    count: 1,
    price: 5670,
    total: 0,
  },
];
